### ISSUE TITLE
The Forgotten Branches + Issue About Publicity

### ISSUE THREAD

**Issue by yehochanan0823** [unlightvbe/unlightvbe_qs_user#10]
@pc01pc013 剛才看了 @gfsd20433 的復刻（fork）發現有兩個分支（branch）被遺忘了，需要看一下嗎？
備註：在網路圖（Network Graph）也能看到那兩個分支。

**Comment by andyciu** [comment]
他的分支好像都是之前版本的產物，而且因為已經是別人所管理的專案嘛，如果有甚麼更新的話也是循pull request來處理這樣

**Comment by gfsd20433** [comment]
那應該是我之前剛用github試着上傳時錯誤留下的branch
因為我要上傳的資料現在都弄好了 那些branch應該已經沒用了
感謝關心 XD

**Comment by yehochanan0823** [comment]
@gfsd20433 瞭解，我記得那些錯誤留下的分支能刪除掉的，是否留下就由你決定了。

**Comment by yehochanan0823** [comment]
對了，我們是否要在網路上做一些宣傳，或者將測試影片公開？
這樣或許會增加一些協助者。

**Comment by andyciu** [comment]
@Hans19980823 一般來講是應該這樣做的，不過尷尬的是因為本專案之特殊性質，本人對此專案一向都採取不做任何宣傳與活動廣告，所以真的也只能採隨緣性質了吧

**Comment by yehochanan0823** [comment]
@pc01pc013 瞭解
