### ISSUE TITLE
常用Buff (和官方原有角色) 的ID衝突

### ISSUE THREAD

**Issue by gfsd20433** [unlightvbe/unlightvbe_qs_user#13]
其實之前也出現類似的問題 就是諾艾菈的那次

然後我發現最近這個版本的"再生"跟我以前寫下的"移動力上升" ID是一樣

雖然"移動力上升"目前是我自己用的 但這個buff其實每個人都有機會用到
如果每個人都用不同ID來做相同的buff就有機會出現到判定的Bug (eg 對方有某個指定buff時...)

所以想問下日後會有個ID表指明哪個官方buff用甚麼ID嗎? @@
之後假如我想要做新的官方buff 可以參考這個ID表
(印象中角色ID表已經有了 但沒有很齊全

**Comment by andyciu** [comment]
感謝您的提問
事實上在之前的時候我特地在wiki上追加了一個新頁面來記載這些資訊
請從Wiki > 「VBE異常狀態／人物實際狀態列表」就可以看到了

**Comment by andyciu** [comment]
對了順便一提，如果是列表當中所沒有的話
原則上就是在提交更新時照列表順序繼續編號下去這樣
基本上至少在此專案可以確保每個都是不重複的

**Comment by gfsd20433** [comment]
喔喔 原來放了在wiki
現在發現這個地方有放到資料 >_>

那就應該沒問題了 感謝
