### ISSUE TITLE
還有繼續開發嗎?

### ISSUE THREAD

**Issue by gfsd20433** [unlightvbe/unlightvbe_qs_user#2]
這邊我試試指出一些常用的事件希望可以追加/修改

狀態:
封印 暈眩 似乎寫不到 <布列表示

執行指令bug:
自身卡牌送與效果執行: 送不到 (不確定)
對某一方擁有之卡牌進行控制: 做不到 自身+手牌出牌(只有同時時,其他如對手+手牌出牌還是做到) 

追加執行指令
對手抽牌
直傷傷害量控制
對手移動操作控制 (eg1:向前/2:向後/3:回復/4:更換角色/5:無)
多階段的更換角色

追加腳本引數變數:
雙方直傷傷害量 
雙方移動力
雙方得到狀態時
雙方移動操作
[執行階段多用途紀錄資訊 執行階段-46(傷害) (3) 中追加] 以自身最大HP值決定的傷害 < 常用於控制對M10使用的即死或HP減半放果

角色bug
艾茵 一顆心 對手沒牌時會有error
史塔夏 殺戮狀態 防禦力會有2倍
格蕾雅 有部分名字誤植: 蕾 -> 蕃
格蕾雅 "氣勢"/"EX氣勢" 發動條件 出防合計3即可發動 而非出防3卡發動

**Comment by andyciu** [comment]
您好，我先快速概略回答一下
首先先說一下我已經蠻久沒有碰VBE了，所以我也只能憑印象中的記憶來回答QAQ

1.暈眩的部分目前的確沒有辦法用指令來寫，但是封印的部分原本構想是利用這個指令-`PersonAtkingOff（禁止人物主動技/被動技能發動效果控制）`來實作，不過我很顯然當時忘記封印是不包含被動技的部分QQ，所以好像也無法。

2.執行指令bug
這部分目前也不清楚，但是或許跟卡牌的篩選條件有關係，因為在`VBEPageCardNumVS`引數中For裡面要篩選「自身」、「手牌」後所剩下的卡牌編號去做指定，才能被指令集接受。

3.追加執行指令/追加腳本引數變數
感謝您的建議:)

4.角色bug
他們bug都是直接改腳本就可以解決的，我之後有空應該會來解，或者您也可以先解一下XD

我最近會把主程式的原始碼git上來，因為這個issue所講的大部分都是面向主程式的部分，再加上這個專案是focus有關人物腳本的部分，所以到時可能要麻煩您再到主程式的專案那邊再開一個issue，這篇issue我就先close。
