### ISSUE TITLE
About Characters

### ISSUE THREAD

**Issue by yehochanan0823** [unlightvbe/unlightvbe_qs_user#7]
V.B.E.歷代（Alpha、Zeta和Q-S）出現的所有角色都會在最終版出現嗎？

**Comment by andyciu** [comment]
這個老實說我也說不準
我本人的立場當然還是希望更多人來更新角色啦，畢竟這才是當初開發QS版的主要目的之一
當然以目前現階段的情形來看光是要讓歷代所有角色都出現在QS版是有一定困難的

**Comment by yehochanan0823** [comment]
瞭解，辛苦作者了。
